exports.FilterType = Object.freeze({
  ALLROOMS: 'allRooms',
  ROOMNUMBER: 'roomNumber',
  INQUIRYBYOBJECTID: 'inquiryByObjectId',
  ADVANCESEARCHINQUIRY: 'advanceSearchInquiry',
  TRANSIENTPRIVATEROOMS: 'transientPrivateRooms',
  TRANSIENTPRIVATEROOMBYOBJECTID: 'transientPrivateRoomByObjectId',
  ADVANCESEARCHTRANSIENTPRIVATEROOMS: 'advanceSearchTransientPrivateRooms',
  BEDSPACEROOMS: 'bedspaceRooms',
  BEDSPACEROOMBYOBJECTID: 'bedspaceRoomByObjectId',
  ADVANCESEARCHBEDSPACEROOMS: 'advanceSearchBedspaceRooms',
  TENANTBYKEYSTROKE: 'tenantByKeyStroke',
  TENANTBYOBJECTID: 'tenantByObjectId',
  ADVANCESEARCHTENANT: 'advanceSearchTenant',
  ALLENTRIES: 'allEntries',
  ENTRYBYOBJECTID: 'entryByObjectId',
  ADVANCESEARCHENTRY: 'advanceSearchEntry',
  ALLROOMPAYMENTS: 'allRoomPayments',
  ROOMPAYMENTBYOBJECTID: 'roomPaymentByObjectId',
  ADVANCESEARCHROOMPAYMENT: 'advanceSearchRoomPayment',
});
