exports.FilterType = Object.freeze({
  ALLROOMS: 'allRooms',
  ROOMNUMBER: 'roomNumber',
  ALLINQUIRIES: 'allInquiries',
  INQUIRYBYOBJECTID: 'inquiryByObjectId',
  ADVANCESEARCHINQUIRY: 'advanceSearchInquiry',
  TRANSIENTPRIVATEROOMS: 'transientPrivateRooms',
  TRANSIENTPRIVATEROOMBYOBJECTID: 'transientPrivateRoomByObjectId',
  ADVANCESEARCHTRANSIENTPRIVATEROOMS: 'advanceSearchTransientPrivateRooms',
  BEDSPACEROOMS: 'bedspaceRooms',
  BEDSPACEROOMBYOBJECTID: 'bedspaceRoomByObjectId',
  ADVANCESEARCHBEDSPACEROOMS: 'advanceSearchBedspaceRooms',
  ALLTENANTS: 'allTenants',
  TENANTBYKEYSTROKE: 'tenantByKeyStroke',
  TENANTBYOBJECTID: 'tenantByObjectId',
  ADVANCESEARCHTENANT: 'advanceSearchTenant',
});
